import React from 'react';
import { motion } from 'framer-motion';
import { FileText, Download, Printer, CheckCircle2 } from 'lucide-react';

export default function ReportPage() {
  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-lg font-bold text-zinc-100">Automated Machine Learning Report Generator</h2>
          <p className="text-xs text-zinc-400">Generate executive summary reports in PDF, DOCX, and Jupyter Notebook formats.</p>
        </div>
        <button className="px-4 py-2 rounded-lg bg-gradient-to-r from-cyan-500 to-blue-600 text-xs font-semibold text-white shadow-lg flex items-center gap-2">
          <Download className="w-3.5 h-3.5" />
          Export Executive Report (PDF)
        </button>
      </div>

      {/* Report Preview Container */}
      <div className="p-8 rounded-2xl glass-panel border border-zinc-800 space-y-6 max-w-4xl mx-auto text-zinc-200">
        <div className="border-b border-zinc-800 pb-4 flex justify-between items-start">
          <div>
            <h1 className="text-xl font-bold text-zinc-100">Automated Machine Learning & XAI Executive Report</h1>
            <p className="text-xs text-zinc-400 mt-1">Generated by Enterprise AI Platform Engine • Date: 2026-07-27</p>
          </div>
          <span className="px-3 py-1 rounded bg-cyan-500/10 text-cyan-400 border border-cyan-500/20 text-xs font-mono">
            CONFIDENTIAL
          </span>
        </div>

        {/* Section 1: Executive Summary */}
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider">1. Executive Summary</h3>
          <p className="text-xs text-zinc-300 leading-relaxed">
            Eksperimen AutoML mengevaluasi 11 algoritma supervised learning pada dataset <span className="font-mono text-cyan-300">customer_churn_v2.csv</span> (7,043 baris). Model <span className="font-semibold text-emerald-400">GradientBoosting</span> terpilih sebagai model terbaik dengan F1-Score sebesar <span className="font-mono font-bold text-emerald-400">96.4%</span> dan ROC-AUC sebesar <span className="font-mono font-bold text-violet-400">0.982</span>.
          </p>
        </div>

        {/* Section 2: Leaderboard Summary */}
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider">2. Leaderboard Metrics Table</h3>
          <div className="p-4 rounded-lg bg-zinc-950/60 border border-zinc-800 text-xs font-mono">
            <p>#1 GradientBoosting  - F1: 96.4% | Acc: 96.5% | ROC-AUC: 0.982 [BEST]</p>
            <p>#2 RandomForest      - F1: 94.8% | Acc: 94.8% | ROC-AUC: 0.965</p>
            <p>#3 XGBoost           - F1: 93.1% | Acc: 93.2% | ROC-AUC: 0.954</p>
          </div>
        </div>

        {/* Section 3: Explainable AI Insights */}
        <div className="space-y-2">
          <h3 className="text-sm font-semibold text-cyan-400 uppercase tracking-wider">3. SHAP Feature Importance</h3>
          <p className="text-xs text-zinc-300">
            Analisis SHAP menunjukkan variabel <span className="font-bold text-zinc-100">Contract_Length</span> dan <span className="font-bold text-zinc-100">Monthly_Charges</span> memiliki kontribusi terbesar terhadap prediksi risiko churn pelanggan.
          </p>
        </div>
      </div>
    </motion.div>
  );
}
